/**
 * AI Service
 *
 * Handles AI backend interactions for:
 * - Custom prompt-based content generation
 * - Ollama LLM integration (local AI)
 * - Content generation and enhancement
 */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';

export interface ScrapedEvent {
  title: string;
  description: string;
  date: string;
  source: string;
  relevance: 'high' | 'medium' | 'low';
  category: string;
}

export interface AIResponse {
  success: boolean;
  response?: string;  // Generated content from custom prompt
  event?: ScrapedEvent;  // Legacy event structure
  error?: string;
  timestamp: string;
}

@Injectable({
  providedIn: 'root'
})
export class AIService {
  constructor(private http: HttpClient) {}

  /**
   * Generate content based on user's custom prompt
   * Connects to Ollama AI backend for local LLM inference
   * 
   * @param prompt User's input text/topic
   */
  fetchCurrentEvent(prompt?: string): Observable<AIResponse> {
    let url = '/api/scrape-event';
    
    // If prompt provided, use it as query parameter
    if (prompt) {
      url += '?prompt=' + encodeURIComponent(prompt);
    }
    
    return this.http.get<AIResponse>(url).pipe(
      catchError(err => {
        console.error('Error fetching content from AI backend:', err);
        return throwError(() => new Error('Failed to fetch content from AI backend'));
      })
    );
  }

  /**
   * Format event data into email-ready text
   */
  formatEventForEmail(event: ScrapedEvent): string {
    return `
=== Current Event Information ===
Title: ${event.title}
Date: ${event.date}
Category: ${event.category}
Source: ${event.source}
Relevance: ${event.relevance.toUpperCase()}

Summary:
${event.description}

---
Generated by AI Web Scraping Service at ${new Date().toLocaleTimeString()}
`.trim();
  }
}
