/**
 * AI Service
 *
 * Handles AI backend interactions for:
 * - Custom prompt-based content generation
 * - Ollama LLM integration (local AI)
 * - Content generation and enhancement
 */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';

export interface ScrapedEvent {
  title: string;
  description: string;
  date: string;
  source: string;
  relevance: 'high' | 'medium' | 'low';
  category: string;
}

export interface AIResponse {
  success: boolean;
  response?: string;  // Generated content from custom prompt
  event?: ScrapedEvent;  // Legacy event structure
  error?: string;
  timestamp: string;
}

export interface RAGQueryResponse {
  success: boolean;
  query: string;
  response: string;
  timestamp: string;
  error?: string;
}

export interface WebSearchResponse {
  success: boolean;
  query: string;
  results: string;
  timestamp: string;
  error?: string;
}

export interface ServiceHealth {
  status: string;
  services: {
    ollama: {
      available: boolean;
      url: string;
      models: string[];
    };
    webSearch: {
      available: boolean;
      configured: boolean;
    };
  };
  timestamp: string;
}

@Injectable({
  providedIn: 'root'
})
export class AIService {
  constructor(private http: HttpClient) {}

  /**
   * Generate content based on user's custom prompt
   * Connects to Ollama AI backend for local LLM inference
   * 
   * @param prompt User's input text/topic
   */
  fetchCurrentEvent(prompt?: string): Observable<AIResponse> {
    let url = '/api/scrape-event';
    
    // If prompt provided, use it as query parameter
    if (prompt) {
      url += '?prompt=' + encodeURIComponent(prompt);
    }
    
    return this.http.get<AIResponse>(url).pipe(
      catchError(err => {
        console.error('Error fetching content from AI backend:', err);
        return throwError(() => new Error('Failed to fetch content from AI backend'));
      })
    );
  }

  /**
   * Modern AI Query with Web Search Integration (RAG)
   * Automatically searches the web for time-sensitive queries
   * 
   * @param query User's question or search query
   * @param useWebSearch Enable/disable automatic web search (default: true)
   * @param model Optional model name to override default
   */
  modernQuery(query: string, useWebSearch: boolean = true, model?: string): Observable<RAGQueryResponse> {
    return this.http.post<RAGQueryResponse>('/api/query', {
      query,
      useWebSearch,
      model
    }).pipe(
      catchError(err => {
        console.error('Error in modern query:', err);
        return throwError(() => new Error(err.error?.error || 'Modern query failed'));
      })
    );
  }

  /**
   * Web Search Only
   * Fetch recent web results without AI processing
   * 
   * @param query Search query
   * @param numResults Number of results to return (default: 5)
   */
  webSearch(query: string, numResults: number = 5): Observable<WebSearchResponse> {
    return this.http.post<WebSearchResponse>('/api/web-search', {
      query,
      numResults
    }).pipe(
      catchError(err => {
        console.error('Error in web search:', err);
        return throwError(() => new Error(err.error?.error || 'Web search not available'));
      })
    );
  }

  /**
   * Check service health
   * Verify Ollama and web search availability
   */
  checkHealth(): Observable<ServiceHealth> {
    return this.http.get<ServiceHealth>('/api/health').pipe(
      catchError(err => {
        console.error('Error checking service health:', err);
        return throwError(() => new Error('Cannot reach backend'));
      })
    );
  }

  /**
   * Format event data into email-ready text
   */
  formatEventForEmail(event: ScrapedEvent): string {
    return `
=== Current Event Information ===
Title: ${event.title}
Date: ${event.date}
Category: ${event.category}
Source: ${event.source}
Relevance: ${event.relevance.toUpperCase()}

Summary:
${event.description}

---
Generated by AI Web Scraping Service at ${new Date().toLocaleTimeString()}
`.trim();
  }

  /**
   * Format RAG response into email-ready text
   */
  formatRAGResponse(query: string, response: string): string {
    return `
=== AI Research Response ===
Query: ${query}

Response:
${response}

---
Generated by Modern RAG Service at ${new Date().toLocaleTimeString()}
`.trim();
  }

  /**
   * Format web search results for email
   */
  formatWebResults(query: string, results: string): string {
    return `
=== Web Search Results for: "${query}" ===

${results}

---
Generated by Web Search Service at ${new Date().toLocaleTimeString()}
`.trim();
  }
}
